import { url } from "inspector"

const test = {
  "query": "curret cypto market growth?",
  "follow_up_questions": null,
  "answer": null,
  "images": [],
  "results": [
    {
      "url": "https://www.fortunebusinessinsights.com/industry-reports/cryptocurrency-market-100149",
      "title": "Cryptocurrency Market Size, Share & Trends Analysis Report, 2034",
      "content": "The cryptocurrency market is growing due to increasing adoption of blockchain technology, rising demand for decentralized finance (DeFi), institutional investments, and regulatory advancements. Enhanced transparency, security, and faster transactions attract users. Additionally, the growing popularity of digital assets and integration with payment systems support continued market expansion globally. Global market exhibited a significant growth of 10.0% in 2020 as compared to year-on-year growth during 2017-2019. [...] loader\n\n##### We appreciate your interest!\n\nThank You\n\n#### THANK YOU\n\n#### Your Request Has Been Received\n\nLooking to go beyond standard insights? Our premium consulting services are available for an additional fee is designed to help you gain a competitive edge.\n\nPlease let us know if you need a deep-dive on any of the following:\n\nloaderdownload\ndownload\n\n## Cryptocurrency Market Size and Industry Overview\n\nPlay Audio\n\nThe global cryptocurrency market size was valued at USD 7.33 billion in 2025. The market is projected to grow from USD 8.47 billion in 2026 to USD 27.02 billion by 2034, exhibiting a CAGR of 15.60% during the forecast period. [...] THANK YOU\n\nYour Request Has Been Received\n\nLooking to go beyond standard insights? Our premium consulting services are <span>available for an additional fee </span>is designed to help you gain a competitive edge.\n\nPlease let us know if you need a deep-dive on any of the following:\n\nThe global cryptocurrency market size is valued at USD 8.47 billion in 2026, projected to reach USD 27.02 billion by 2034 at a CAGR of 15.60% during 2026–2034.\n\nRead More at:-\n\nSubscribe News Letter\n\nTrust Online\n\nDMCA.com Protection Status\nComodo Secure\n\nContact Us\n\nConnect with us\n\nInformation\n\nRecognized By\n\nComodo Secure\n\nD&B D-U-N-S®   \n Number: 861494523\n\nGreat place to work\nISO 1\nISO 1\nISO 1\n\n© 2026 Fortune Business Insights . All rights reserved\n\nTop Arrow\n\nto enhance your experience.",
      "score": 0.78473216,
      "raw_content": null,
      "favicon": "https://dosrg0qttcg52.cloudfront.net/img/fav_icon/favicon.png"
    },
    {
      "url": "https://www.mordorintelligence.com/industry-reports/cryptocurrency-market",
      "title": "Cryptocurrency Market Size, Trends, Industry Outlook 2031",
      "content": "## Key Questions Answered in the Report\n\nThe Cryptocurrency market size reached USD 6.16 trillion in market value in 2026 and is projected to reach USD 20.01 trillion by 2031 at a 26.56% CAGR.\n\nTrading and Investment Transfers led with 49.52% in 2025 and the same segment is projected to grow at 31.24% CAGR through 2031, maintaining leadership in the Cryptocurrency market.\n\nInstitutional users held 63.24% in 2025, while Retail is forecast to grow fastest at 28.33% CAGR as mobile-first access expands in the Cryptocurrency market.\n\nNorth America led with 35.38% in 2025, and Asia-Pacific is the fastest-growing region with a projected 29.24% CAGR to 2031 in the Cryptocurrency market. [...] Cryptocurrency Market (2026 - 2031)\n\n## Cryptocurrency Market Analysis by Mordor Intelligence\n\nThe Cryptocurrency Market size is expected to increase from USD 4.87 trillion in 2025 to USD 6.16 trillion in 2026 and reach USD 20.01 trillion by 2031, growing at a CAGR of 26.56% over 2026-2031. [...] Growth in the Cryptocurrency market is shifting from speculative retail cycles toward regulated utility as institutions adopt compliant access products and settlement rails in core economies. Momentum is reinforced by the launch and scaling of spot exchange-traded products, which expanded fiduciary access and normalized crypto within portfolio construction frameworks across advisory platforms. Transaction activity continues to consolidate around payments, remittances, and institutional trading flows as stablecoin usage rises and compliance standards harden in the United States and the European Union. Stablecoin transaction volumes expanded strongly through 2025, reinforcing payment utility and settlement use cases as core adoption vectors within the crypto market.\n\nKey Report Takeaways",
      "score": 0.741169,
      "raw_content": null,
      "favicon": "https://s3.mordorintelligence.com/favicon.ico"
    },
    {
      "url": "https://www.technavio.com/report/cryptocurrency-market-industry-analysis",
      "title": "Cryptocurrency Market Growth Analysis - Size and Forecast 2026-2030",
      "content": "## What are the Key Data Covered in this Cryptocurrency Market Research and Growth Report?\n\n   What is the expected growth of the Cryptocurrency Market between 2026 and 2030?\n\n       USD 137.68 billion, at a CAGR of 25.1%\n\n   What segmentation does the market report cover?\n\n       The report is segmented by Type (Bitcoin, Ethereum, and Others), Application (Trading and investment, Payments and remittances, and Others), End-user (Retail, and Institutional) and Geography (North America, APAC, Europe, Middle East and Africa, South America)\n\n   Which regions are analyzed in the report?\n\n       North America, APAC, Europe, Middle East and Africa and South America\n\n   What are the key growth drivers and market challenges? [...] | Market Scope |\n\n| Page number | 289 |\n| Base year | 2025 |\n| Historic period | 2020-2024 |\n| Forecast period | 2026-2030 |\n| Growth momentum & CAGR | Accelerate at a CAGR of 25.1% |\n| Market growth 2026-2030 | USD 137678.0 million |\n| Market structure | Fragmented |\n| YoY growth 2025-2026(%) | 20.9% |\n| Key countries | US, Canada, Mexico, India, Vietnam, Indonesia, The Philippines, Thailand, South Korea, Ukraine, Russia, UK, Germany, France, Italy, Nigeria, Egypt, South Africa, UAE, Saudi Arabia, Brazil, Argentina and Colombia |\n| Competitive landscape | Leading Companies, Market Positioning of Companies, Competitive Strategies, and Industry Risks |\n\nRequest Free Sample\n\n## Research Analyst Overview [...] ### Major Market Trends & Insights\n\n   North America dominated the market and accounted for a 34.4% growth during the forecast period.\n   By Type - Bitcoin segment was valued at USD 33.53 billion in 2024\n   By Application - Trading and investment segment accounted for the largest market revenue share in 2024\n\n### Market Size & Forecast\n\n   Market Opportunities: USD 171.18 billion\n   Market Future Opportunities: USD 137.68 billion\n   CAGR from 2025 to 2030 : 25.1%\n\n### Market Summary",
      "score": 0.7380092,
      "raw_content": null,
      "favicon": "https://www.technavio.com/image/catalog/favicon.png"
    },
    {
      "url": "https://www.grandviewresearch.com/industry-analysis/cryptocurrency-market-report",
      "title": "Cryptocurrency Market Size & Share | Industry Report, 2033",
      "content": "## Cryptocurrency Market Summary\n\n  The global cryptocurrency market size is estimated at USD 6.34 billion in 2025 and is projected to reach USD 18.26 billion by 2033, growing at a CAGR of 14.5% from 2026 to 2033. The increasing adoption of distributed ledger technology is expected to drive the growth of the cryptocurrency industry during the forecast period.\n\n  ### Key Market Trends & Insights [...] ## Frequently Asked Questions About This Report\n\n  How big is the cryptocurrency market?\n\n  b.  The global cryptocurrency market size was estimated at USD 6.34 billion in 2025 and is expected to reach USD 7.08 billion in 2026.\n\n  What is the cryptocurrency market growth?\n\n  b.  The global cryptocurrency market is expected to grow at a compound annual growth rate of 14.5% from 2026 to 2033 to reach USD 18.26 billion by 2033.\n\n  Which segment accounted for the largest cryptocurrency market share?\n\n  b.  The Asia Pacific dominated the cryptocurrency market with a share of 31.0% in 2025. The presence of cryptocurrency mining companies such as Ebang International Holdings, Inc., Bitmain Technologies Limited., Canaan, Inc., and others are expected to support the market growth in the region. [...] The growing prominence of cryptocurrency as a decentralized asset class has drawn significant investment from private venture firms, contributing to the market's ongoing expansion. In November 2024, the cryptocurrency industry reached a remarkable milestone, with its total market capitalization hitting a record high of USD 3.2 trillion, according to CoinGecko. This surge in value reflects a growing interest and investment in various cryptocurrencies, driven by factors such as increased institutional adoption, advancements in blockchain technology, and the expansion of decentralized finance (DeFi) platforms.",
      "score": 0.73755574,
      "raw_content": null,
      "favicon": "https://www.grandviewresearch.com/favicon.ico"
    },
    {
      "url": "https://www.statista.com/outlook/fmo/digital-assets/cryptocurrencies/worldwide?srsltid=AfmBOoq0WZuBrX923UA_EU9BBhYNumegkfR1IEkt5WSuhiebmpvFeJM-",
      "title": "Cryptocurrencies - Worldwide | Statista Market Forecast",
      "content": "The cryptocurrency market showed renewed momentum in 2025, driven by institutional adoption, growing interest in tokenized assets, and regulatory clarity in key markets like the U.S. and Europe. Bitcoin has regained investor confidence, while Ethereum’s upgrade continues to attract developers and DeFi projects. Stablecoins are increasingly integrated into traditional finance, bridging crypto and fiat systems.   \n AI, gaming, and real-world asset (RWA) tokenization are emerging as key innovation areas. ETFs and crypto investment products have opened the door to broader participation from risk-averse investors. Regulatory developments, particularly MiCA in Europe and clearer tax frameworks in the U.S., are reducing uncertainty. [...] 1. Market Insights\n2. Finance\n3. Digital Assets\n\n# Cryptocurrencies- Worldwide\n\nWorldwide\n\n Revenue in the Cryptocurrencies market is projected to reach US$96.1bn in 2026.\n The average revenue per user in the Cryptocurrencies market amounts to US$96.7 in 2026.\n From a global comparison perspective it is shown that the highest revenue is reached United States (US$17.2bn in 2026).\n In the Cryptocurrencies market, the number of users is expected to amount to 993.64m users by 2026.\n User penetration will be 12.63% in 2026 and is expected to hit 12.63% by 2026.\n\n Key regions:\n United Kingdom,\n Brazil,\n United States,\n Germany,\n South Korea\n\nDefinition: [...] However, the market remains volatile. Price swings driven by macroeconomic shifts, interest rates, or regulatory crackdowns can still unsettle even large-cap coins. Security breaches and scams remain a persistent risk, particularly in DeFi. Looking ahead, long-term growth will depend on infrastructure maturity, energy efficiency improvements, and global cooperation on standards. While the market holds high upside, especially in areas like cross-border payments and decentralized identity, it is still speculative and highly sensitive to sentiment.",
      "score": 0.56920683,
      "raw_content": null,
      "favicon": "https://cdn.statcdn.com/static/img/apple-touch-icon-precomposed.png"
    }
  ],
  "response_time": 1.69,
  "request_id": "af7e4179-f330-4d2c-b8df-331ccfb07967"
}

test.results.map(result => ({url : result.url}))